In [37]:
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

In [11]:
iris = load_iris()

X = iris.data
y = iris.target

y = to_categorical(y)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
scaler = StandardScaler()

In [16]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
model = Sequential()
model.add(Dense(10, input_shape=(4,), activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [19]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [20]:
model.fit(X_train, y_train, epochs=20, batch_size=5, validation_split=0.2)

Epoch 1/20
20/20 [==============================] - 1s 15ms/step - loss: 1.0284 - accuracy: 0.2292 - val_loss: 1.0109 - val_accuracy: 0.2083
Epoch 2/20
20/20 [==============================] - 0s 2ms/step - loss: 0.9828 - accuracy: 0.3125 - val_loss: 0.9488 - val_accuracy: 0.3333
Epoch 3/20
20/20 [==============================] - 0s 2ms/step - loss: 0.9338 - accuracy: 0.6146 - val_loss: 0.9071 - val_accuracy: 0.5833
Epoch 4/20
20/20 [==============================] - 0s 3ms/step - loss: 0.8861 - accuracy: 0.7708 - val_loss: 0.8632 - val_accuracy: 0.7083
Epoch 5/20
20/20 [==============================] - 0s 3ms/step - loss: 0.8370 - accuracy: 0.7604 - val_loss: 0.8271 - val_accuracy: 0.7500
Epoch 6/20
20/20 [==============================] - 0s 2ms/step - loss: 0.7858 - accuracy: 0.8229 - val_loss: 0.7734 - val_accuracy: 0.7917
Epoch 7/20
20/20 [==============================] - 0s 2ms/step - loss: 0.7322 - accuracy: 0.8854 - val_loss: 0.7315 - val_accuracy: 0.7917
Epoch 8/20
20/20 [=

In [32]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Loss: , {loss:.2f}")
print(f"Accuracy: , {accuracy:.2f}")

1/1 [==============================] - 0s 16ms/step - loss: 0.3308 - accuracy: 0.9333
Loss: , 0.33
Accuracy: , 0.93


In [62]:
predictions = model.predict(X_test)
print(np.round(predictions[:5], 3))

1/1 [==============================] - 0s 15ms/step
[[0.035 0.547 0.418]
 [0.975 0.002 0.023]
 [0.    0.21  0.789]
 [0.048 0.518 0.434]
 [0.008 0.466 0.526]]
