In [1]:
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

In [2]:
iris = load_iris()

X = iris.data
y = iris.target

y = to_categorical(y)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
scaler = StandardScaler()

In [5]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [6]:
model = Sequential()
model.add(Dense(10, input_shape=(4,), activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [7]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [8]:
model.fit(X_train, y_train, epochs=20, batch_size=5, validation_split=0.2)

Epoch 1/20
20/20 [==============================] - 1s 14ms/step - loss: 1.0181 - accuracy: 0.3646 - val_loss: 1.0696 - val_accuracy: 0.2917
Epoch 2/20
20/20 [==============================] - 0s 2ms/step - loss: 0.9483 - accuracy: 0.4062 - val_loss: 1.0094 - val_accuracy: 0.3750
Epoch 3/20
20/20 [==============================] - 0s 3ms/step - loss: 0.8876 - accuracy: 0.5208 - val_loss: 0.9553 - val_accuracy: 0.5833
Epoch 4/20
20/20 [==============================] - 0s 2ms/step - loss: 0.8357 - accuracy: 0.6250 - val_loss: 0.9092 - val_accuracy: 0.7500
Epoch 5/20
20/20 [==============================] - 0s 2ms/step - loss: 0.7899 - accuracy: 0.7083 - val_loss: 0.8664 - val_accuracy: 0.7500
Epoch 6/20
20/20 [==============================] - 0s 2ms/step - loss: 0.7443 - accuracy: 0.7500 - val_loss: 0.8276 - val_accuracy: 0.8333
Epoch 7/20
20/20 [==============================] - 0s 2ms/step - loss: 0.7060 - accuracy: 0.7708 - val_loss: 0.7859 - val_accuracy: 0.8333
Epoch 8/20
20/20 [=

In [9]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Loss: , {loss:.2f}")
print(f"Accuracy: , {accuracy:.2f}")

1/1 [==============================] - 0s 16ms/step - loss: 0.3285 - accuracy: 0.9000
Loss: , 0.33
Accuracy: , 0.90


In [10]:
predictions = model.predict(X_test) 
print(np.round(predictions[:5], 3))

1/1 [==============================] - 0s 60ms/step
[[0.138 0.472 0.39 ]
 [0.982 0.016 0.002]
 [0.018 0.121 0.861]
 [0.145 0.417 0.438]
 [0.103 0.329 0.568]]
