In [21]:
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

In [22]:
iris = load_iris()

X = iris.data
y = iris.target

y = to_categorical(y)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
scaler = StandardScaler()

In [25]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [26]:
model = Sequential()
model.add(Dense(10, input_shape=(4,), activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [27]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [28]:
model.fit(X_train, y_train, epochs=20, batch_size=5, validation_split=0.2)

Epoch 1/20
20/20 [==============================] - 0s 11ms/step - loss: 1.0113 - accuracy: 0.3854 - val_loss: 1.0100 - val_accuracy: 0.5000
Epoch 2/20
20/20 [==============================] - 0s 2ms/step - loss: 0.9358 - accuracy: 0.5312 - val_loss: 0.9470 - val_accuracy: 0.6250
Epoch 3/20
20/20 [==============================] - 0s 2ms/step - loss: 0.8709 - accuracy: 0.5417 - val_loss: 0.8952 - val_accuracy: 0.6667
Epoch 4/20
20/20 [==============================] - 0s 2ms/step - loss: 0.8116 - accuracy: 0.6042 - val_loss: 0.8506 - val_accuracy: 0.7083
Epoch 5/20
20/20 [==============================] - 0s 2ms/step - loss: 0.7576 - accuracy: 0.6458 - val_loss: 0.8030 - val_accuracy: 0.7500
Epoch 6/20
20/20 [==============================] - 0s 3ms/step - loss: 0.7104 - accuracy: 0.6771 - val_loss: 0.7545 - val_accuracy: 0.7917
Epoch 7/20
20/20 [==============================] - 0s 2ms/step - loss: 0.6706 - accuracy: 0.7083 - val_loss: 0.7188 - val_accuracy: 0.8333
Epoch 8/20
20/20 [=

In [29]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Loss: , {loss:.2f}")
print(f"Accuracy: , {accuracy:.2f}")

1/1 [==============================] - 0s 20ms/step - loss: 0.3301 - accuracy: 0.9333
Loss: , 0.33
Accuracy: , 0.93


In [32]:
predictions = model.predict(X_test) 
print(np.round(predictions[:5], 3))

1/1 [==============================] - 0s 16ms/step
[[0.159 0.472 0.369]
 [0.992 0.002 0.005]
 [0.013 0.071 0.915]
 [0.142 0.435 0.423]
 [0.109 0.424 0.467]]
